Othello/config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'users#index'
  get 'signup' =>'users#new'

end

Othello/app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: {maximum:50}

  has_secure_password
  validates :password, presence: true, length: {minimum:6} 
end

Othello/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Othello/app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    render action: 'index'
  end
end

Othello/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end
  def signup
    @users=User.all
  end
  def show
    @user=User.find(params[:id])
    #debugger
  end
  def new
    @user=User.new
  end
  def create
    @user=User.new(user_params)
    if @user.save
      flash[:success] = "Successfully created..."
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name,:password,:password_confirmation)
    end
end

Othello/app/helpers/application_helper.rb
module ApplicationHelper
end

Othello/app/helpers/game_helper.rb
module GameHelper
end

Othello/app/helpers/users_helper.rb
module UsersHelper
  #引数で与えられたユーザのGravatar画像を返す
  def gravatar_for(user)
    #gravatar_id =Digest::MD5::hexdigest(user .email .downcase)
    #gravatar_url="https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url,alt: user.name, class: "gravatar")
  end
end

Othello/app/views/game/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <script type="text/javascript">
                //Imageオブジェクトを生成して、画像ファイルを先読みしておく
                var img_board = new Image();
                var img_black = new Image();
                var img_white = new Image();
                img_board.src = "assets/board.png";
                img_black.src = "assets/black.png";
                img_white.src = "assets/white.png";

                var game = new Game();
                var board = new Board();
                var playerColor = new Array(1);


            </script>
        </head>
        <body height="550" onLoad="setGame(game,board,playerColor)">

            <canvas width="500" height="500" id="othello"></canvas>
            <p id="turn"></p>
            <p id="gameset"></p>

            <form>
                <input type="radio" name="player" checked onclick="setPlayerBlack(game,playerColor)">黒
                <input type="radio" name="player" onclick="setPlayerWhite(game,playerColor)">白
                <input type="button" value="start" onclick="GameStart(game,board,playerColor)">
                <input type="button" value="reset" onclick="GameReset(game,board,playerColor)">
            </form>
        </body>
    </html>

Othello/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" >
  <div calss="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", '#' %></li>
        <li><%= link_to "Log in ", '/signup' %></li>
      </ul>
    </nav>
  </div>
</header>

Othello/app/views/layouts/_shim.html.erb
<!--[if It IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"
</script>
<![endif]-->

Othello/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Othello</title>
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Othello/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Othello</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layout/shim' %>
</head>
<body>
  <!-- #render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type,message| %>
    <div class="alert alert-<%= message_type %>"><%= message %> </div>
    <% end %>
    <%= yield %>
   render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </div>
-->



  <%= render 'layout/header' %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

Othello/app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %> </td>
    <td><%= link_to 'Destroy', user,method: :delete, data: {confirm: 'Are you sure?' }%></td>
  </tr>
  <% end %>
</table>
<br>
<%=link_to 'New User', new_user_path %>

Othello/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1> Sign up </h1>

<div class="row">
  <div class="col-md-6 col-md-ofset-3">
    <%= form_for(@user) do |f| %>
    <%= f.label :name,"name" %>
    <%= f.text_field :name %>

    <%= f.label :password,"password" %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation,"Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Create my account" , class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

Othello/app/views/users/show.html.erb
<% provide(:title,@user.name) %>
<h1>
  <%= gravatar_for @user %>
  <% @user.name %>
</h1>

Othello/app/views/users/signup.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
  <li><%= user.name  %>login </li>
  <% end %>
</ul>